spring:
  application:
    name: ms-tarifas-especiales
  config:
    import: configserver:http://config-service:8888
  cloud:
    config:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update