server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # La opción `lower-case-service-id` es útil para estandarizar los IDs de servicio.
          # Si tus IDs de servicio en Eureka no son exactamente en minúsculas, esto los convierte.
          lower-case-service-id: true
      routes:
        # --- Ruta para ms-clientes ---
        - id: ms-clientes-route
          uri: lb://MS-CLIENTES # 'lb://' indica Load Balancer, MS-CLIENTES es el ID de servicio en Eureka
          predicates:
            - Path=/api/clientes/** # Cualquier solicitud que empiece con /api/clientes/ irá a ms-clientes
          filters:
            - RewritePath=/api/clientes/(?<segment>.*), /cliente/${segment} # Reescritura de la URL