server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # --- Ruta para ms-clientes ---
        - id: ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/cliente/**

        #----------------------------------------
        - id: ms-tarifas-duracion
          uri: lb://ms-tarifas-duracion
          predicates:
              - Path=/tarifas/**
        #---------------------------------------
        - id: ms-descuentos-personas
          uri: lb://ms-descuentos-personas
          predicates:
              - Path=/descuentos-persona/**
        #--------------------------------------
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
              - Path=/reservas/**
        #---------------------------------------
        - id: ms-descuentos-frecuentes
          uri: lb://ms-descuentos-frecuentes
          predicates:
            - Path=/descuentos-frecuencia/**
        #---------------------------------------
        - id: ms-tarifas-especiales
          uri: lb://ms-tarifas-especiales
          predicates:
            - Path=/tarifas-especiales/**

        #---------------------------------------
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/reportes/**
        #---------------------------------------
        - id: ms-admin
          uri: lb://ms-admin
          predicates:
            - Path=/administrador/**
