server:
  port: 8080 # Asegúrate de que tu Gateway esté realmente en este puerto. Si lo ejecutas en 8081, cámbialo aquí.

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # --- Ruta para ms-clientes ---
        - id: ms-clientes-route
          uri: lb://MS-CLIENTES # Deja este en MAYÚSCULAS para que coincida con el registro por defecto de Eureka
          predicates:
            - Path=/api/clientes/**
          filters:
            - RewritePath=/api/clientes/(?<segment>.*), /cliente/${segment}