server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  eureka:
    instance:
      preferIpAddress: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://eureka-service:8761/eureka/