server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Reserva
    username: postgres
    password: "0370"

  mail:
    host: smtp.gmail.com
    port: 587
    username: jorgemunoz0371@gmail.com
    password: cesxodobtuogdyxb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  eureka:
    instance:
      hostname: localhost
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka
