spring:
  application:
    name: ms-descuentos-frecuentes
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update