apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-admin-deployment
  labels:
    app: ms-admin-deployment
spec:
  selector:
    matchLabels:
      app: ms-admin-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-admin-deployment
    spec:
      containers:
        - name: ms-admin
          image: jorge370/ms-admin:latest
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ADMIN
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ADMIN
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ADMIN
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_ADMIN
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_ADMIN
