apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-clientes-deployment
  labels:
    app: ms-clientes-deployment
spec:
  selector:
    matchLabels:
      app: ms-clientes-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-clientes-deployment
    spec:
      containers:
        - name: ms-clientes
          image: jorge370/ms-clientes:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CLIENTES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CLIENTES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CLIENTES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CLIENTES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CLIENTES
---
apiVersion: v1
kind: Service
metadata:
  name: ms-clientes-service
spec:
  selector:
    app: ms-clientes-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
