apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-admin-deployment
  labels:
    app: postgres-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-admin
  template:
    metadata:
      labels:
        app: postgres-admin
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-admin-service
spec:
  selector:
    app: postgres-admin
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
