apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: QWRtaW4=           # Admin
  POSTGRES_USER: cG9zdGdyZXM=     # postgres
  POSTGRES_PASSWORD: MDM3MA==     # 0370
