apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-reservas-deployment
  labels:
    app: ms-reservas-deployment
spec:
  selector:
    matchLabels:
      app: ms-reservas-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-reservas-deployment
    spec:
      containers:
        - name: ms-reservas
          image: jorge370/ms-reservas:latest
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_RESERVAS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_RESERVAS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_RESERVAS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_RESERVAS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_RESERVAS
