apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tarifas-duracion-deployment
  labels:
    app: ms-tarifas-duracion-deployment
spec:
  selector:
    matchLabels:
      app: ms-tarifas-duracion-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tarifas-duracion-deployment
    spec:
      containers:
        - name: ms-tarifas-duracion
          image: jorge370/ms-tarifas-duracion:latest
          ports:
            - containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TARIFAS_DURACION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_TARIFAS_DURACION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_TARIFAS_DURACION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_TARIFAS_DURACION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_TARIFAS_DURACION
