server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Jorge12121/Evaluacion2Tingeso/tree/main/config-data
          search-paths: config-data
  application:
    name: config-service
